version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-for-springboot
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: post_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
