version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-for-springboot
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
      MYSQL_DATABASE: post_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
